config/routes.rb
SteamWatch::Application.routes.draw do
  resources :games do
    resources :extras, :controller => "games/extras"
  end

  root :to => "games#index"
end

app/models/extra.rb
class Extra < ActiveRecord::Base
  include PriceAwareness
  attr_accessible :metascore, :name, :release_date, :extra_type,:url,:extra_type
  has_many :prices, :as => :buyable
  belongs_to :game

  def find_game_belongs_to
    words = name.gsub(/[^a-z0-9 ]/i,"").split
    my_game = nil
    while words.pop
      my_game = Game.where("name LIKE ?","#{words.join(" ")}%").first
      break if my_game || words.length == 1
     end
     my_game
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  include PriceAwareness
  attr_accessible :metascore, :name, :release_date,:url, :steam_id
  has_many :prices, :as => :buyable
  has_many :extras
  def self.all_with_price
    Game.includes(:prices).first.prices
  end
end

app/models/price.rb
class Price < ActiveRecord::Base
  attr_accessible :game_id, :ammount, :start_date
  belongs_to :buyable, :polymorphic => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games/extras_controller.rb
class Games::ExtrasController < ApplicationController

  def index
    @extras = Extra.find_all_by_game_id params["game_id"]
  end
  def show
    @extra = Extra.find params["id"]
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    # @games = Game.all
    respond_to do |format|
      format.html
      format.json { render json: GamesDatatable.new(view_context)}
    end
  end
  def show
    @game = Game.find params[:id]
    respond_to do |format| 
      format.html
      format.json {render json: [@game.to_json,@game.prices.to_json,@game.extras]}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_price_history(prices)
    prices.inject("") do |html,price|
      html + "<li>$#{price.ammount.to_s} on #{price.start_date.to_s}</li>"
    end
  end
end

app/helpers/games/extras_helper.rb
module Games::ExtrasHelper
end

app/helpers/games_helper.rb
module GamesHelper

end

app/views/games/extras/index.html.erb
<ul>
<% @extras.each do |extra| %>
  <li><%= link_to extra.name, game_extra_path(extra.game_id,extra.id) %></li>
  <% end %>
</ul>

app/views/games/extras/show.html.erb
<h1><%= @extra.name %></h1>
<p><%= @extra.release_date %></p>
<ul> 
<%= raw show_price_history(@extra.prices) %>
</ul>

app/views/games/index.html.erb
<div class="container">
  <div class="span12">
      <div class="span4 right-col">
          <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="games" data-source="<%= games_url(format: "json") %>">
            <thead>
            <tr>
              <th>Game Name</th>
              <th>Price</th>
              <th>Metascore</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
      </div>

    <div class="offset4 span6 left-col">
      <div class="span4 info">
        <h6 class ="title"><span></span></h6>
        <ul class="information">
          <li class="released"><span></span></li>
          <li class="steam_link"><a></a></li>
        </ul>
      </div>
      <br />
      <div class="span6 priceHistory">
        <h6>Price History:</h6>
        <ul>
        </ul>
      </div>
      <br />
      <div class="span6 extras">
        <h6>Extras(beta):</h6>
        <ul>

        </ul>
      </div>
    </div>
  </div>    
  
  </div>
</div>

app/views/games/show.html.erb
<h3><%= @game.name %></h3>
<ul>
  <li>released on <%=@game.release_date %></li>
  <li>price history:</li>
  <ul>
    <%= raw show_price_history(@game.prices) %>
  </ul>
</ul>
<ul>
<% @game.extras.each do |extra| %>
  <li><%= link_to extra.name, game_extra_path(extra.game_id,extra.id) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SteamWatch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>